### ISSUE TITLE
No node found for selector: #SignIn-emailInput

### ISSUE THREAD

**Issue by zeryl** [Shmakov/kroger-cli#2] opened 2020-06-20 01:33 UTC
Fresh git pull from today, using kroger.com for my sign-in, and get this when attempting to perform any action. 

pyppeteer.errors.PageError: No node found for selector: #SignIn-emailInput`

**Comment by zeryl** [comment] 2020-06-20 01:41
This ONLY is happening on Linux, Python 3.7m.  Downloaded the pre-built Windows binary, and it's working.

**Comment by Shmakov** [comment] 2020-06-23 22:45
Thanks for the bug report @zeryl!

I was able to reproduce it, however not sure at this point on how to fix it.

It seem to happen because the kroger's websites detects headless-chrome bot like activity and denies access to the website.

Adjusting the User-Agent doesn't work, I will see if I can come up with a workaround.

**Comment by tieubao81** [comment] 2020-08-19 20:10
Looks like the pre-compiled Windows binary is not working either.  I get this error:

Please select from one of the options: 4
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Signing in.. (please wait, it might take awhile)
Traceback (most recent call last):
  File "kroger_cli\__main__.py", line 51, in <module>
  File "lib\site-packages\click\core.py", line 829, in __call__
  File "lib\site-packages\click\core.py", line 782, in main
  File "lib\site-packages\click\core.py", line 1236, in invoke
  File "lib\site-packages\click\core.py", line 1066, in invoke
  File "lib\site-packages\click\core.py", line 610, in invoke
  File "lib\site-packages\click\decorators.py", line 21, in new_func
  File "kroger_cli\__main__.py", line 16, in cli
  File "kroger_cli\cli.py", line 86, in prompt_options
  File "kroger_cli\cli.py", line 155, in option_points_balance
  File "kroger_cli\memoize.py", line 28, in __call__
  File "kroger_cli\api.py", line 41, in get_points_balance
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "kroger_cli\api.py", line 157, in _get_points_balance
  File "kroger_cli\api.py", line 234, in sign_in_routine
  File "kroger_cli\api.py", line 254, in sign_in
  File "lib\site-packages\pyppeteer\page.py", line 1546, in click
  File "lib\site-packages\pyppeteer\frame_manager.py", line 583, in click
pyppeteer.errors.PageError: No node found for selector: #SignIn-emailInput
[24852] Failed to execute script __main__

**Comment by Shmakov** [comment] 2021-03-01 17:53
Duplicate of #6

**Closed as completed by Shmakov** 2021-03-01 17:53 UTC
