### ISSUE TITLE
Application closes on sign-in attempt

### ISSUE THREAD

**Issue by ThatOneAsswipe** [Shmakov/kroger-cli#5] opened 2021-01-04 04:24 UTC
Initial setup and sign-in successful, coupon clipping opened Chromium, but redirected to "access denied" page. Closed application and disabled VPN for troubleshooting purposes. Cached account info still displays, but any sign-in attempt does not open Chromium, and closes the application. Restarted VPN, application close issue persists.

Upon recording video of error, found the text "Traceback (most recent call last):" displaying very briefly before application closes.

**Comment by hskrtich** [comment] 2021-02-11 22:20
I am having the same issue when trying to login to a Fred Meyer account

Here is the Traceback that I am getting

```
Please select preferred store [1]: 7
─────────────────────
In order to continue, please enter your username (email) and password for kroger.com (also works with Ralphs, Dillons,
Smith’s and other Kroger’s Chains)
Username (email): bskrtich@gmail.com
Password: D4GM%MSUPERPASSWORD
Traceback (most recent call last):
  File "kroger_cli\__main__.py", line 4, in <module>
  File "kroger_cli\cli.py", line 24, in __init__
  File "kroger_cli\cli.py", line 33, in init
  File "kroger_cli\cli.py", line 58, in prompt_credentials
  File "kroger_cli\cli.py", line 114, in _set_credentials
  File "configparser.py", line 1259, in __setitem__
  File "configparser.py", line 1201, in set
  File "configparser.py", line 894, in set
  File "configparser.py", line 402, in before_set
ValueError: invalid interpolation syntax in 'D4GM%MSUPERPASSWORD' at position 4
[18092] Failed to execute script __main__
```

Please note that isnt my real password.

**Comment by ThermoMan** [comment] 2021-02-25 01:02
I had the same error logging into a Kroger account.

```
+---------------------------------------------------------------------------------------------------------------------+
|Welcome to Kroger CLI (unofficial command line interface)                                                            |
+---------------------------------------------------------------------------------------------------------------------+
1 - Display account info
2 - Clip all digital coupons
3 - Purchases Summary
4 - Points Balance
5 - Complete Kroger’s Survey (to earn 50 points)
8 - Re-Enter username/password
9 - Exit
Please select from one of the options: 1
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Signing in.. (please wait, it might take awhile)
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "KrogerCLI.py", line 81, in prompt_options
  File "KrogerCLI.py", line 147, in _option_account_info
  File "Memoize.py", line 28, in __call__
  File "KrogerAPI.py", line 37, in get_account_info
  File "asyncio\runners.py", line 43, in run
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "KrogerAPI.py", line 139, in _get_account_info
  File "KrogerAPI.py", line 234, in sign_in_routine
  File "KrogerAPI.py", line 254, in sign_in
  File "lib\site-packages\pyppeteer\page.py", line 1546, in click
  File "lib\site-packages\pyppeteer\frame_manager.py", line 583, in click
pyppeteer.errors.PageError: No node found for selector: #SignIn-emailInput
[18844] Failed to execute script main
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "lib\site-packages\pyppeteer\launcher.py", line 151, in _close_process
  File "asyncio\base_events.py", line 591, in run_until_complete
  File "asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

On repeated executions the Chromium window does not even open.

Task manager shows MANY instance of Chromium (with a blue logo) running.  On killing all of them and trying again.  I get six instances of Chromium in the task Manager from one attempt to "Display account info"

I am opening a command line and running it from that.  The results are no different on double clicking the icon, except there is no opportunity to see the error messages.

**Comment by Shmakov** [comment] 2021-03-01 17:53
Duplicate of #6

**Closed as completed by Shmakov** 2021-03-01 17:53 UTC
