### ISSUE TITLE
Sign in errors in both Linux & Windows

### ISSUE THREAD

**Issue by ceefus** [Shmakov/kroger-cli#4] opened 2020-09-10 22:27 UTC
Please select from one of the options: 1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Signing in.. (please wait, it might take awhile)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ceefus/kroger-cli/kroger_cli/__main__.py", line 51, in <module>
    cli()
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ceefus/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ceefus/kroger-cli/kroger_cli/__main__.py", line 16, in cli
    kroger_cli.prompt_options()
  File "/home/ceefus/kroger-cli/kroger_cli/cli.py", line 80, in prompt_options
    self.option_account_info()
  File "/home/ceefus/kroger-cli/kroger_cli/cli.py", line 146, in option_account_info
    info = self.api.get_account_info()
  File "/home/ceefus/kroger-cli/kroger_cli/memoize.py", line 28, in __call__
    value = self.func(*args)
  File "/home/ceefus/kroger-cli/kroger_cli/api.py", line 37, in get_account_info
    return asyncio.get_event_loop().run_until_complete(self._get_account_info())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ceefus/kroger-cli/kroger_cli/api.py", line 139, in _get_account_info
    signed_in = await self.sign_in_routine()
  File "/home/ceefus/kroger-cli/kroger_cli/api.py", line 234, in sign_in_routine
    signed_in = await self.sign_in(redirect_url, contains)
  File "/home/ceefus/kroger-cli/kroger_cli/api.py", line 254, in sign_in
    await self.page.click('#SignIn-emailInput', {'clickCount': 3})  # Select all in the field
  File "/home/ceefus/venv/lib/python3.8/site-packages/pyppeteer/page.py", line 1546, in click
    await frame.click(selector, options, **kwargs)
  File "/home/ceefus/venv/lib/python3.8/site-packages/pyppeteer/frame_manager.py", line 583, in click
    raise PageError('No node found for selector: ' + selector)
pyppeteer.errors.PageError: No node found for selector: #SignIn-emailInput

Running headless I see Chromium trying to sign in but it says sign in failed.

**Comment by Shmakov** [comment] 2021-03-01 17:53
Duplicate of #6

**Closed as completed by Shmakov** 2021-03-01 17:53 UTC
